#!/bin/sh -e
#
#    byobu-launcher
#    Copyright (C) 2008 Canonical Ltd.
#
#    Authors: Nick Barcet <nick.barcet@ubuntu.com>
#             Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


[ "$TERM" = "screen" ] && exit 0

# Ensure that the PROMPT_COMMAND gets printed, such that gnome-terminal
# and friends can pick it up before going into screen
[ -x /bin/bash ] && echo "echo 'Launching Byobu...'" | /bin/bash -i -s 2>/dev/null

out=`screen -ls 2>/dev/null` || true
if echo "$out" | grep -qsi "^No Sockets found in "; then
	# Start new byobu session
	exec byobu
else
	# Re-attach to an existing session
	exec screen -xRR
fi
