#!/bin/sh -e
#
#    byobu-select-profile
#    Copyright (C) 2008 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#             Nick Barcet <nick.barcet@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


# If you change any strings, please generate localization information with:
#	./debian/rules get-po

PKG="byobu"

TEXTDOMAIN="$PKG"

COLORS="black blue cyan green purple red grey yellow"

usage () {
    cat <<EOT
Usage: $0 [(-l|--list)][(-h|--help)]
    -l,--list           list available profiles
    -b,--background	set the background color
    -f,--foreground     set the foreground color
    -h,--help           this help

    Without any parameters, runs interactively.
EOT
}

# Initialize variables
FILE="$HOME"/."$PKG"/color
PROFILE="$HOME/.$PKG/profile"
[ -r "$PROFILE" ] || ln -sf /usr/share/$PKG/profiles/common "$PROFILE"
selected=-1
color=

assert_symlink() {
	if [ -e "$1" ]; then
		if [ ! -L "$1" ]; then
			echo `gettext 'Error:'` $1 `gettext ' file exists, but is not a symlink'`
			exit 1
		fi
	fi
}

mkdir -p "$HOME/.$PKG"
# If these files exist, they must be a symlink
assert_symlink "$HOME/.$PKG/profile"

listprofiles() {
	# Display list of profiles, one per line
	for x in $COLORS; do
		echo "dark_$x"
		echo "light_$x"
	done
}

prompt() {
	which="$1"
	count=1
	selected=-1
	while /bin/true; do
		if [ $count -gt 5 ]; then
			echo `gettext "ERROR: Invalid selection"`
			exit 1
		fi
		count=$(expr $count + 1)
		echo
		if [ "$which" = "foreground" ]; then
			echo `gettext 'Select the foreground color: '`
			simple="black"
		else
			echo `gettext 'Select the background color: '`
			simple="grey"
		fi
		i=1
		for x in $COLORS; do
			test $i -lt 10 2>/dev/null && echo -n "  " || echo -n " "
			echo "$i. $x"
			i=$(expr $i + 1)
			[ "$simple" = "$x" ] && simple=$i
			test $i -lt 10 2>/dev/null && echo -n "  " || echo -n " "
			echo "$i. $x (light)"
			i=$(expr $i + 1)
		done
		echo
		if [ -z "$selected" -a -n "$simple" ]; then
			selected="$simple"
		elif ! test $selected -gt 0 2>/dev/null; then
			echo -n "`gettext 'Choose'` 1-$i [$simple]: "
			selected=`head -n1`
		elif ! test $selected -le $i 2>/dev/null; then
			echo -n "`gettext 'Choose'` 1-$i [$simple]: "
			selected=`head -n1`
		else
			i=1
			for x in $COLORS; do
				color="dark_$x"
				[ "$i" = "$selected" ] && break
				i=$(expr $i + 1)
				color="light_$x"
				[ "$i" = "$selected" ] && break
				i=$(expr $i + 1)
			done
			echo `gettext "Selected"` "$which [$color]"
			setcolor "$which" "$color"
			return 0
		fi
	done
}

getletter() {
	count=$(echo "$1" | wc -c)
	if [ "$count" = "2" ]; then
		echo "$1"
		return
	fi
	desc=$(echo "$1" | awk -F"_" '{print $1}')
	color=$(echo "$1" | awk -F"_" '{print $2}')
COLORS="black blue cyan green purple red grey yellow"

	case $color in
		black)  letter="k";;
		blue)   letter="b";;
		cyan)   letter="c";;
		green)  letter="g";;
		purple) letter="m";;
		red)    letter="r";;
		grey)  letter="w";;
		yellow) letter="y";;
		*)      letter="w";;
	esac
	if [ "$desc" = "light" ]; then
		letter=$(echo "$letter" | tr "[:lower:]" "[:upper:]")
	fi
	echo "$letter"
}

setcolor() {
	which="$1"
	color="$2"
	[ -r $FILE ] && . $FILE
	if [ "$which" = "foreground" ]; then
		FOREGROUND=$(getletter "$color")
	else
		BACKGROUND=$(getletter "$color")
	fi
	printf "FOREGROUND=$FOREGROUND\nBACKGROUND=$BACKGROUND\n" > $FILE
	touch "/var/run/screen/S-$USER/$PKG.reload-required"
}

if [ $# -eq 0 ]; then
	prompt "background"
	prompt "foreground"
	screen -X at 0 source "$HOME/.$PKG/profile"
else
	while true; do
		case "$1" in
			-b|--background)
				setcolor "background" "$2"
				shift 2
			;;
			-f|--foreground)
				setcolor "foreground" "$2"
				shift 2
			;;
			-l|--list)
				listprofiles
				shift
				break
			;;
			*)
				usage
				exit 1
			;;
			--)
				shift
				break
			;;
		esac
		[ $# -eq 0 ] && break
	done
fi

exit 0
