#!/bin/sh -e
#
#    byobu-status
#    Copyright (C) 2008 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

###########################################################
# We should be really "nice" about gathering status:
#renice 10 $$ >/dev/null 2>&1 || true
#ionice -c3 -p $$ >/dev/null 2>&1 || true
# However, this *really* slows down startup.
# We need a good way of only doing this for updates,
# but not at screen startup.
###########################################################

PKG="byobu"

if [ -d "$HOME/.$PKG/bin" ]; then
	DIR="$HOME/.$PKG/bin"
elif [ -d "/usr/lib/$PKG" ]; then
	DIR="/usr/lib/$PKG"
else
	exit 1
fi

P="$1"
B='\033[34;1m'
W='\033[47m'
X='\033[0m'
HR="                                                                               "

case "$P" in
	# default = on, user must override to turn off
	cpu-count|cpu-freq|date|load-average|logo|mem-available|mem-used|menu|reboot-required|release|time|updates-available|uptime)
		grep -qs -m1 "^$P=0$" "$HOME/.$PKG/status" && exit 0
	;;
	# default = off, user must override to turn on
	arch|battery|ec2-cost|hostname|ip-address|network-down|network-up|processes|users|whoami|wifi-quality)
		grep -qs -m1 "^$P=1$" "$HOME/.$PKG/status" || exit 0
	;;
	--detail)
		printf "\033[1m"
		[ -x "/usr/bin/dpkg-query" ] && /usr/bin/dpkg-query --show $PKG | awk '{print "# $PKG (" $2 ") detailed status:"}'
		printf "$X\n"
		for i in `ls "$DIR"`; do
			[ "$i" = "menu" ] && continue
			printf "\n$W%s$X\n" "$HR"
			printf "$W $X $B# %s:$X\n" "$i"
			out=`"$DIR"/$i --detail | sed 's/^/\\\033[47m \\\033[0m    /g'` || true
			printf "$out\n"
			printf "$W%s$X\n\n" "$HR"
		done
		exit 0
	;;
	*)
		exit 1
	;;
esac

if [ -f "$DIR"/"$P" -a -x "$DIR"/"$P" ]; then
	exec "$DIR"/"$P"
fi
