.TH byobu 1 "11 Feb 2009" byobu "byobu"
.SH NAME
byobu \- wrapper script for seeding a user's byobu configuration and launching screen

.SH DESCRIPTION
\fBbyobu\fP is a simple script that sanitizes a user's ~/.byobu directory, and launches screen in the byobu configuration.

.TP
\fIhttp://launchpad.net/byobu\fP
.PD

.SH AUTHOR
This manpage and the utility was written by Dustin Kirkland <kirkland@canonical.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
