#!/bin/sh
#
#    byobu - screen wrapper script
#    Copyright (C) 2008-2009 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG="byobu"
VERSION=2.19

# Add a version argument for debugging purposes
if [ "$1" = "-v" ]; then
	echo "$PKG version $VERSION"
	screen -v
	exit 0
fi

# Nesting byobu inside of screen doesn't work well
if [ "$TERM" = "screen" ]; then
	echo `gettext "Exit the current screen session to run $PKG"`
	exit 1
fi

# Sanitize the environment
byobu-janitor --force

# Launch motd+shell, unless the user has default windows set to launch
[ -n "$SHELL" ] || SHELL="/bin/sh"
[ -x "$SHELL" ] || SHELL="/bin/sh"
DEFAULT_WINDOW="$SHELL -c motd+shell"
grep -qs "^[^#]" "$HOME/.$PKG/windows" && DEFAULT_WINDOW=

# Now let's execute screen!
if [ "$#" = "0" ]; then
	exec screen -c "/usr/share/$PKG/profiles/byoburc" $DEFAULT_WINDOW
else
	exec screen -c "$HOME/.$PKG/profile" "$@"
fi
