#!/bin/sh -e
#
#    byobu - screen wrapper script
#    Copyright (C) 2008-2009 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG="byobu"
VERSION=2.46

# Add a version argument for debugging purposes
if [ "$#" = "1" ] && [ "$1" = "-v" ]; then
	echo "$PKG version $VERSION"
	screen -v
	exit 0
fi

# Nesting byobu inside of screen doesn't work well
if [ -n "$STY" ] || [ "$TERM" = "screen-bce" ]; then
	echo `gettext "Exit the current screen session to run $PKG"`
	exit 1
fi

# Sanitize the environment
byobu-janitor --force

# Set window title until https://bugs.launchpad.net/bugs/338722 is fixed in screen
printf "\033]0;${USER}@$(hostname) - ${PKG}\007"

# Launch motd+shell, unless the user has default windows set to launch
grep -qs "^[^#]" "$HOME/.$PKG/windows" && DEFAULT_WINDOW= || DEFAULT_WINDOW="motd+shell"

# Now let's execute screen!
if [ "$#" = "0" ]; then
	exec screen -c "/usr/share/$PKG/profiles/byoburc" -t shell $DEFAULT_WINDOW
else
	exec screen -c "$HOME/.$PKG/profile" "$@"
fi
