#!/bin/bash
#
#    GNU screen-profiles-helper
#    Copyright (C) 2008 Canonical Ltd.
#
#    Authors: Nick Barcet <nick.barcet@ubuntu.com>
#             Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


install_screen_launcher() {
	dest=$1
	launcher="/usr/bin/screen-launcher"
	# We have to make sure screen is called last
	pos=$(( $(grep -ns "$launcher" "$dest" | sed 's/:.*$//' | head -1) ))

	do=0
	if [ $pos -gt 0 ]; then
		if [ $pos -lt $(( $(wc -l "$dest" | sed "s/ .*$//") -2)) ]; then
			# We have to reposition the line at the end
			# First remove it
			sed -ibak '/screen-launcher/d' "$dest"
			do=1
		fi
	else
		do=1
	fi
	# Add it at the end
	if [ $do -eq 1 ]; then
		echo "$launcher" >> "$dest"
	fi
}

install_screen_launcher "$HOME/.bashrc"
install_screen_launcher "$HOME/.bash_profile"

