#!/bin/sh -e
#
#    screen-launcher-install
#    Copyright (C) 2008 Canonical Ltd.
#
#    Authors: Nick Barcet <nick.barcet@ubuntu.com>
#             Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG="byobu"

install_screen_launcher() {
	dest=$1
	launcher="screen-launcher"
	launcher_line="\`echo \$- | grep -qs i\` && $launcher"
	# Add it at the end
	echo "$launcher_line" >> "$dest"
	# Hush login, since byobu will handle motd printing
	touch "$HOME"/.hushlogin
}

# Sanitize the environment
/usr/share/$PKG/screen-launcher-uninstall || true

# Install in $HOME/.profile unconditionally
install_screen_launcher "$HOME/.profile"

# Install in zprofile if default shell is zsh
if grep -qs "^$USER:.*zsh$" /etc/passwd; then
	install_screen_launcher "$HOME/.zprofile"
fi

# Now, install in any shell-specific profiles, if they exist
# This list may grow to support other shells
for i in ".bash_profile" ".bash_login"; do
	if [ -w "$HOME/$i" ]; then
		install_screen_launcher "$HOME/$i"
	fi
done
