.TH screen\-profiles 1 "16 Jan 2009" screen-profiles "screen-profiles"
.SH NAME
screen\-profiles \- Configuration utility for screen\-profiles

.SH DESCRIPTION
\fBscreen\-profiles\fP is an application that can configure a number of options available in the screen\-profiles utility.

The menu provided by the \fBscreen\-profiles\fP should be self-explanatory.

.SH "BUGS"

PuTTY users have reported that the F2, F3, and F4 shortcut keys are not working properly.  PuTTY sends the same escape sequences as the linux console for F1-F4 by default.  You can fix this problem in the PuTTY config by changing the function keys to 'xterm R6'.  See: \fIhttp://www.mail-archive.com/screen-users@gnu.org/msg01525.html\fP

.SH "SEE ALSO"
.PD 0
.TP
\fBscreen\fP(1)

.TP
\fIhttp://launchpad.net/screen-profiles\fP
.PD

.SH AUTHOR
This manpage was written by Dustin Kirkland <kirkland@canonical.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
