#!/bin/sh
#
#    screen wrapper script
#    Copyright (C) 2008 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Create the screen-profiles directory, if it doesn't already exist
[ -d "$HOME/.screen-profiles" ] || mkdir -p "$HOME/.screen-profiles"

# Use $SCREENRC if non-empty, and readable; otherwise, use the one in $HOME
[ -n "$SCREENRC" -a -r "$SCREENRC" ] || SCREENRC="$HOME/.screenrc"

# If $SCREENRC exists but $HOME/.screen-profiles/profile does not,
# this shows that the user has an existing custom screen configuration,
# and thus we will not force screen-profiles on them.
if [ -r "$SCREENRC" -a ! -e "$HOME/.screen-profiles/profile" -a ! -h "$HOME/.screen-profiles/profile" ]; then
	exec /usr/bin/screen.real -c "$SCREENRC" "$@"
	exit $?
fi

DEFAULT_PROFILE="light"

# Ensure that the user has selected a screen profile
profile="$HOME/.screen-profiles/profile"
[ -h "$profile" ] || /usr/bin/select-screen-profile -s "$DEFAULT_PROFILE"

# Previously, profiles were prepended with ubuntu-.
# This is no longer the case, for cross-distro compatibility.
# Try to fix broken symlinks for upgrading users, or prompt to reselect.
if [ -h "$profile" -a ! -r "$profile" ]; then
	if stat "$profile" | head -n1 | grep -qs ".*->.*ubuntu\-.*"; then
		newsrc=$(stat "$profile" | head -n1 | sed "s/.*\`//" | sed "s/'.*//" | sed "s/ubuntu-//")
		if [ -r "$newsrc" ]; then
			ln -sf "$newsrc" "$profile"
		else
			/usr/bin/select-screen-profile -s "$DEFAULT_PROFILE"
		fi
	elif stat "$profile" | head -n1 | grep -qs ".*->.*plain'$"; then
		ln -sf "/usr/share/screen-profiles/profiles/NONE" "$profile"
	else
		/usr/bin/select-screen-profile -s "$DEFAULT_PROFILE"
	fi
fi

if [ ! -r "$profile" ]; then
	echo
	echo "Your selected profile is not accessible."
	echo
	echo "Either select a different profile:"
	echo " $ select-screen-profile"
	echo
	echo "Or install the extras package:"
	echo " $ sudo apt-get install screen-profiles-extras"
	echo
	exit 1
fi

# Ensure that their keybindings are seeded
[ -s "$HOME/.screen-profiles/keybindings" ] || echo "source /usr/share/screen-profiles/keybindings/common" > "$HOME/.screen-profiles/keybindings"

# Ensure that their default windows are seeded
[ -r "$HOME/.screen-profiles/windows" ] || touch "$HOME/.screen-profiles/windows"

# Ensure that the user's $SCREENRC at least exists
[ -r "$SCREENRC" ] || touch "$SCREENRC"

# Now let's execute screen!
if [ "$#" = "0" ]; then
	# Create a temporary config file *with* the default windows
	# but if we refresh, we'll just source the profile, without
	temp=$(mktemp screen-profiles-XXXXXXXX)
	trap "rm -f $temp 2>/dev/null || true" EXIT HUP INT QUIT TERM
	cat "$HOME/.screen-profiles/profile" "$HOME/.screen-profiles/windows" > "$temp"
	[ -n "$SHELL" -a -x "$SHELL" ] || SHELL="/bin/sh"
	exec /usr/bin/screen.real -c "$temp" $SHELL /usr/bin/motd+shell
else
	exec /usr/bin/screen.real -c "$HOME/.screen-profiles/profile" "$@"
fi
