#!/bin/sh -e
#
#    screen-launcher-install
#    Copyright (C) 2008 Canonical Ltd.
#
#    Authors: Nick Barcet <nick.barcet@ubuntu.com>
#             Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


install_screen_launcher() {
	dest=$1
	launcher="/usr/bin/screen-launcher"
	launcher_line="[ -x $launcher ] && $launcher"
	# We have to make sure screen is called last
	pos=$(( $(grep -ns "$launcher" "$dest" | sed 's/:.*$//' | head -1) ))
	do=0
	if [ $pos -gt 0 ]; then
		if [ $pos -lt $(( $(wc -l "$dest" | sed "s/ .*$//") -2)) ]; then
			# We have to reposition the line at the end
			# First remove it
			sed -i '/\/usr\/bin\/screen-launcher$/d' "$dest"
			do=1
		fi
	else
		do=1
	fi
	# Add it at the end
	if [ $do -eq 1 ]; then
		echo "$launcher_line" >> "$dest"
	fi
}

# Sanitize the environment
/usr/share/screen-profiles/screen-launcher-uninstall || true

# Install in ~/.profile unconditionally
install_screen_launcher "$HOME/.profile"

# Now, install in any shell-specific profiles, if they exist
# This list may grow to support other shells
for i in ".bash_profile" ".bash_login"; do
	if [ -w "$HOME/$i" ]; then
		install_screen_launcher "$HOME/$i"
	fi
done
