#!/bin/sh -e
#
#    screen-launcher
#    Copyright (C) 2008 Canonical Ltd.
#
#    Authors: Nick Barcet <nick.barcet@ubuntu.com>
#             Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Sanitize the local user's setup
for i in ".screenrc-keybindings" ".screenrc-windows"; do
	if [ ! -e "$HOME/$i" ]; then
		touch "$HOME/$i"
	fi
done

# Launch screen
if [ "$TERM" != "screen" ]; then
	screen -xRR
fi
