#!/bin/sh
#
#    screen-profiles-status-detail
#    Copyright (C) 2008 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

pager=
for i in "sensible-pager" "less" "more"; do
	if which "$i" >/dev/null 2>&1; then
		pager="$i"
		break
	fi
done

if [ -n "$pager" ]; then
	screen-profiles-status --detail | $pager
else
	screen-profiles-status --detail
fi
