#!/bin/sh -e

BASE_DIR="/usr/share/screen-profiles"
PROFILE_DIR="$BASE_DIR/profiles"

# Ensure that ~/.screenrc-profile is a symbolic link
if [ -e "$HOME/.screenrc-profile" ]; then
	if [ ! -L "$HOME/.screenrc-profile" ]; then
		echo `gettext 'Error:'` $HOME/.screenrc-profile `gettext 'exists, but is not a symlink'`
		exit 1
	fi
fi

# Prompt the user to choose among the available profiles
echo
echo "Select a screen profile: "
i=0
profiles=$(ls $PROFILE_DIR)
for x in $profiles; do
	i=$(expr $i + 1)
	desc="          "
	if [ $x = "ubuntu.screenrc" ]; then
		desc="<---- ` gettext 'recommended'`"
		simple=$i
	fi
	echo "  $i. $x\t\t$desc"
done
echo
selected=x
while /bin/true; do
	if [ -z "$selected" -a ! -z "$simple" ]; then
		selected="$simple"
	elif ! test $selected -gt 0 2>/dev/null; then
		read -p "`gettext 'Choose'` 1-$i [$simple]: " -r selected
	elif ! test $selected -le $i 2>/dev/null; then
		read -p "`gettext 'Choose'` 1-$i [$simple]: " -r selected
	else
		break
	fi
done

i=0
for x in $profiles; do
	i=`expr $i + 1`
	if [ $i -eq $selected ]; then
		if [ ! -e "$HOME/.screenrc" ]; then
			# If the user doesn't have a .screenrc, seed one
			echo "source ~/.screenrc-profile" > "$HOME/.screenrc"
		else
			# If the user does have a .screenrc, see if it has the
			# source line
			if ! grep -qs "source $HOME/.screenrc-profile" "$HOME/.screenrc"; then
				# And if it's missing the source line, add it
				# to the top
				tmp=`mktemp "$HOME/.screenrc.XXXXXX"`
				echo "source $HOME/.screenrc-profile" > "$tmp"
				cat "$HOME/.screenrc" >> "$tmp"
				mv -f "$tmp" "$HOME/.screenrc"
			fi
		fi
		rm -f "$HOME/.screenrc-profile"
		ln -s "$PROFILE_DIR/$x" "$HOME/.screenrc-profile"
	fi
done

exit 0
