#!/usr/bin/env python3
"""trustmux — Trustmux daemon."""
import sys
import os

_here = os.path.dirname(os.path.abspath(__file__))
if os.path.isdir(os.path.join(_here, "trustmux")):
    sys.path.insert(0, _here)
else:
    sys.path.insert(0, "/usr/lib/trustmux")

from trustmux._daemon import main

if __name__ == "__main__":
    main()
