#!/bin/sh -e
#
#    apport: note if there are crash dumps available for apporting
#    Copyright (C) 2009 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG="byobu"
color 2>/dev/null || color() { true; }

if [ "$1" = "--detail" ]; then
	if ls /var/crash/*.crash >/dev/null 2>&1; then
		printf "\nTo file bugs on the existing crash reports, run:\n"
		which apport-cli >/dev/null || printf "  sudo apt-get install apport\n"
		for i in /var/crash/*.crash; do
			printf "  apport-cli $i\n"
		done
		printf "\nTo clear the pending reports:\n"
		printf "  rm -f /var/crash/*.crash\n\n"
	else
		printf "No pending crash reports\n"
	fi
	exit 0
fi

# Print {!} if a /var/crash/*.crash file exists
ls /var/crash/*.crash >/dev/null 2>&1 && printf "$(color y k){!}$(color -) "
