#!/bin/sh -e
#
#    color: print the background/foreground color escape codes
#
#    Copyright (C) 2011 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

__color_detail() {
	true
}

__color() {
	[ -z "$FOREGROUND" ] && FOREGROUND="w"
	[ -z "$BACKGROUND" ] && BACKGROUND="k"
	case "$BYOBU_BACKEND" in
		tmux)
			true
		;;
		*)
			printf "\005{= $BACKGROUND$FOREGROUND}"
		;;
	esac
}

# vi: syntax=sh ts=4 noexpandtab
