#!/bin/sh -e
#
#    cpu_count: count cpu's on a systems
#
#    Copyright (C) 2008 Canonical Ltd.
#    Copyright (C) 2011-2014 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@byobu.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

__cpu_count_detail() {
	if [ -r /proc/cpuinfo ]; then
		grep -i "^model name" /proc/cpuinfo
	elif [ "$(uname -s)" = "OpenBSD" ]; then
		sysctl -n hw.model 2>/dev/null
	fi
}

__cpu_count() {
	local c
	c=$(getconf _NPROCESSORS_ONLN 2>/dev/null || sysctl -n hw.ncpuonline 2>/dev/null || grep -ci "^processor" /proc/cpuinfo 2>/dev/null || echo 1)
	[ "$c" = "1" ] || printf "%sx" "$c"
}

# vi: syntax=sh ts=4 noexpandtab
