#!/bin/sh -e
#
#    custom: run the user's custom status scripts
#
#    Copyright (C) 2009 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG="byobu"
DATA="$HOME/.$PKG"
[ -d "$DATA/bin" ] || exit 0
color 2>/dev/null || color() { true; }

[ -d "/var/run/screen/S-$USER" ] && DIR="/var/run/screen/S-$USER" || DIR="$DATA"
NOW=$(date +%s)
CACHE="$DIR/$PKG.custom"

# Loop over custom scripts
for i in "$DATA/bin/"[0-9]*_*; do
	[ -x "$i" ] || continue
	script=${script##*/}
	freq=${script%%_*}
	freq=${freq#0}
	[ -r "$CACHE.$script.last" ] && read lastrun "$CACHE.$script.last" ||
		lastrun=0
	expiration=$(($lastrun+$freq))
	if [ $NOW -ge $expiration ]; then
		"$i" "$@" > "$CACHE.$script" 2>/dev/null
		echo "${NOW}" > "$CACHE.$script.last"
	fi
	readfile < "$CACHE.$script"
	output="${_RET}"
	case "$output" in
		*"$ESC{"*)
			# User has formatted the colors
			printf "$output"
		;;
		*)
			# Default to inverted coloring
			color invert; printf "%s" "$output"; color --
		;;
	esac
done
