#!/bin/sh -e
#
#    date: print the date in YYYY-MM-DD format
#
#    Copyright (C) 2008 Canonical Ltd.
#    Copyright (C) 2011 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@byobu.co>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

__date_detail() {
	date
}

__date() {
	case "$BYOBU_BACKEND" in
		screen)
			color none; printf "\005Y-\005m-\005d"; color --
		;;
	esac
}

# vi: syntax=sh ts=4 noexpandtab
