#!/bin/sh -e
#
#    ec2_cost: approximate EC2 cost (USD) of the current instance
#
#    Copyright (C) 2008 Canonical Ltd.
#    Copyright (C) 2011-2014 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@byobu.co>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Data Transfer Cost Basis
# Incoming	$0.01/GB
# Outgoing	$0.12/GB
# (This gets more complex if you use >10TB/mo)
RX_RATE="0.01"
TX_RATE="0.12"

__ec2_cost_detail() {
	DETAIL=1
	__ec2_cost
}

__ec2_cost() {
	local zone type file_to_stat cpu mem rate hours tx_gb rx_gb network_cost uptime_cost total_cost interface cache="$BYOBU_RUN_DIR/cache.$BYOBU_BACKEND/ec2_cost"
	if [ -s "$cache.rate" ]; then
		read rate < "$cache.rate"
	elif metadata_available; then
		# Try to use metadata service
		[ -s "$cache.zone" ] || wget -q -O- http://169.254.169.254/latest/meta-data/placement/availability-zone </dev/null >"$cache.zone" 2>/dev/null &
		sleep 0.02
		[ -s "$cache.zone" ] && read zone < "$cache.zone"
		zone=${zone%%[a-z]}
		[ -s "$cache.type" ] || wget -q -O- http://169.254.169.254/latest/meta-data/instance-type </dev/null >"$cache.type" 2>/dev/null &
		sleep 0.02
		[ -s "$cache.type" ] && read type < "$cache.type"
		$BYOBU_PREFIX/lib/byobu/include/ec2instancespricing.py --type ondemand --filter-region $zone --filter-type $type --filter-os-type linux --format csv | tail -n1 > "$cache.rate"
		read rate < "$cache.rate"
	fi
	if [ -z "$rate" ]; then
		# Unknown rate, exit immediately
		# Rate estimation is now deprecated
		return
	fi
	rate=${rate##*,}
	file_to_stat="/etc/hostname"
	hours=$(((`date +%s` - `stat --printf %Y $file_to_stat`) / 60 / 60 + 1))
	# Auto detect network interface
	[ -r "/proc/net/route" ] || return
	interface=$(tail -n1 /proc/net/route  | awk '{print $1}')
	local iface rbytes rpackets rerrs rdrop rfifo rframe rcompressed rmulticast tbytes tpackets terrs tdrop tfifo tcolls tcarrier tcompressed
	while read iface rbytes rpackets rerrs rdrop rfifo rframe rcompressed rmulticast tbytes tpackets terrs tdrop tfifo tcolls tcarrier tcompressed; do
		case "$iface" in
			${interface}:)
				tx_gb=${tbytes}
				rx_gb=${rbytes}
				break;
			;;
			${interface}:*)
				# Interface and rbytes got munged together
				tx_gb=${rmulticast##*:}
				rx_gb=${iface##*:}
				break;
			;;
		esac
		if [ "$iface" = "${interface}:" ]; then
			tx_gb=${tbytes}
			rx_gb=${rbytes}
			break
		fi
	done < /proc/net/dev
	tx_gb=$(printf "%s" ${tx_gb} | awk '{ printf "%f", $1 / 1024 / 1024 / 1024 }')
	rx_gb=$(printf "%s" ${rx_gb} | awk '{ printf "%f", $1 / 1024 / 1024 / 1024 }')
	network_cost=`printf "%s %s %s %s" "$tx_gb" "$TX_RATE" "$rx_gb" "$RX_RATE" | awk '{printf "%f %f", $1*$2, $3*$4}' | awk '{printf "%f", $1 + $2}'`
	# Calculate uptime cost
	uptime_cost=`printf "%s" "$hours" | awk "{printf \"%f\", "$rate" * $hours}"`
	total_cost=`printf "%s %s" "$network_cost" "$uptime_cost" | awk '{printf "%.2f", $1 + $2}'`
	if [ "$DETAIL" = "1" ]; then
		echo "================================================"
		echo "Estimated cost in Amazon's EC2 since last reboot"
		echo "================================================"
		echo "  Network sent:  $tx_gb GB   @ \$$RX_RATE/GB"
		echo "  Network recv:  $rx_gb GB   @ \$$TX_RATE/GB"
		echo "  Network cost:  \$$network_cost"
		echo "------------------------------------------------"
		echo "  Uptime:        $hours hr  @ \$$rate/hr"
		echo "  Uptime cost:   \$$uptime_cost"
		echo "------------------------------------------------"
		echo "Total cost:      ~\$$total_cost"
		echo "================================================"
		return
	fi
	[ -n "$total_cost" ] || return
	color K G; printf "A\$"; color -; color b K G; printf "%s" "$total_cost"; color --
}

# vi: syntax=sh ts=4 noexpandtab
