#!/bin/sh -e
#
#    entropy: system entropy
#
#    Copyright (C) 2011 Dustin Kirkland <dustin.kirkland@gmail.com>
#
#    Authors: Dustin Kirkland <dustin.kirkland@gmail.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

__entropy_detail() {
	cat /proc/sys/kernel/random/entropy_avail
}

__entropy() {
	local e=$(cat /proc/sys/kernel/random/entropy_avail)
	[ -n "$e" ] || return
	color K Y; printf "e%s" "$e"; color --
}

# vi: syntax=sh ts=4 noexpandtab
