#!/bin/sh -e
#
#    hostname - report a host's name
#    Copyright (C) 2008-2011 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG="byobu"
DATA="$HOME/.$PKG"
color 2>/dev/null || color() { true; }

if [ "$1" = "--detail" ]; then
	hostname -f
	exit 0
fi

if wget -q -O- --timeout=1 http://169.254.169.254 2>&1; then
	# We're in EC2, so get our public hostname
	h=$(wget -q -O - http://169.254.169.254/latest/meta-data/public-hostname)
else
	h=$(hostname -s 2>/dev/null || hostname)
fi

color bold2; printf "%s" "$h"; color --

# vi: syntax=sh ts=4 noexpandtab
