#!/bin/sh -e
#
#    hostname: report a host's name
#
#    Copyright (C) 2008-2011 Canonical Ltd.
#    Copyright (C) 2011 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

__hostname_detail() {
	hostname -f
}

__hostname() {
	if metadata_available; then
		# We're in EC2, so get our public hostname
		h=$(wget -q -O - http://169.254.169.254/latest/meta-data/public-hostname)
	else
		h=$(hostname -s 2>/dev/null || hostname)
	fi
	color bold2; printf "%s" "$h"; color --
}

# vi: syntax=sh ts=4 noexpandtab
