#!/bin/sh -e
#
#    hostname: report a host's name
#
#    Copyright (C) 2008-2011 Canonical Ltd.
#    Copyright (C) 2011-2014 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@byobu.co>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

__hostname_detail() {
	hostname -f
}

__hostname() {
	local h=
	if metadata_available; then
		local cache="$BYOBU_RUN_DIR/cache.$BYOBU_BACKEND/hostname"
		# Background a retrieval of our public hostname
		wget -q -O- http://169.254.169.254/latest/meta-data/public-hostname </dev/null >"$cache" 2>/dev/null &
		sleep 0.02
		[ -s "$cache" ] && read h < "$cache"
	else
		h=$(hostname -s 2>/dev/null || hostname)
	fi
	[ -n "$h" ] || return
	color bold2; printf "%s" "$h"; color --
}

# vi: syntax=sh ts=4 noexpandtab
