#!/bin/sh -e
#
#    ip_address - report a host's ip address
#    Copyright (C) 2008 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG="byobu"
DATA="$HOME/.$PKG"
color 2>/dev/null || color() { true; }

if [ "$1" = "--detail" ]; then
	[ -x /sbin/ifconfig ] && /sbin/ifconfig
	/sbin/ip -4 addr list
	/sbin/ip -6 addr list
	exit 0
fi

. "$DATA/status"

# Allow interface overrides in $DATA/statusrc
if [ -n "$MONITORED_NETWORK" ]; then
	interface="$MONITORED_NETWORK"
else
	case "$IPV6" in
		1|true|yes) interface=$(grep -v "\Wlo$" /proc/net/ipv6_route | tail -n1 | awk '{print $10}') ;;
		*) interface=$(tail -n1 /proc/net/route  | awk '{print $1}') ;;
	esac
fi

case "$IPV6" in
	1|true|yes)
		ipaddr=$(LC_ALL=C /sbin/ip -6 addr list dev "$interface" scope global)
		# Print 'None' if we have no global address
		[ -z "$ipaddr" ] && ipaddr="None"
		ipaddr=${ipaddr#* inet6 }
		ipaddr=${ipaddr%%/*}
	;;
	*)
		ipaddr=$(LC_ALL=C /sbin/ip -4 addr list dev "$interface" scope global)
		ipaddr=${ipaddr#* inet }
		ipaddr=${ipaddr%%/*}
	;;
esac

color bold2; printf "%s" "$ipaddr"; color --
