#!/bin/sh -e
#
#    mail: notify the user if they have system mail
#    Copyright (C) 2009 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG="byobu"
color 2>/dev/null || color() { true; }
[ "$UTF8" = "1" ] && ICON="⍌" || ICON="[M]"

mailfile="/var/spool/mail/$USER"
if [ "$1" = "--detail" ]; then
	[ -s "$mailfile" ] && ls -alF "$mailfile" 2>&1
	exit 0
fi

if [ -s "$mailfile" ]; then
	 color b; printf "%s" "$ICON"; color --
fi

# vi: syntax=sh ts=4 noexpandtab
