#!/bin/sh -e
#
#    mail: notify the user if they have system mail
#
#    Copyright (C) 2009 Canonical Ltd.
#    Copyright (C) 2011-2014 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@byobu.co>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

MAILFILE="/var/spool/mail/$USER"

__mail_detail() {
	[ ! -d "$MAILFILE" ] && [ -s "$MAILFILE" ] && ls -alF "$MAILFILE" 2>&1
	[ -d "$MAILFILE/new" ] && ls -AlF "$MAILFILE/new" 2>&1
}

__mail() {
	if [ -f "$MAILFILE" ] && [ -s "$MAILFILE" ]; then
		 color b; printf "%s" "$ICON_MAIL"; color --
	elif [ -d "$MAILFILE/new" ] && "$(ls -A "$MAILFILE/new" 2>/dev/null)"; then
		 color b; printf "%s" "$ICON_MAIL"; color --
	else
		rm -f "$BYOBU_RUN_DIR/status.$BYOBU_BACKEND/mail"*
	fi
}

# vi: syntax=sh ts=4 noexpandtab
