#!/bin/sh -e
#
#    mem: grab the current memory and usage
#    Copyright (C) 2008 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG="byobu"
DATA="$HOME/.$PKG"
color 2>/dev/null || color() { true; }

if [ "$1" = "--detail" ]; then
	free
	exit 0
fi

mem_available_info() {
	local mem_used comma whitespace unit mem name
	. "$DATA/status"
	[ "$mem_used" = "1" ] && comma="," || whitespace=" "

	read name mem unit < /proc/meminfo
	if [ $mem -ge 1048576 ]; then
		fpdiv "$mem" 1048567 1
		mem=${_RET}
		unit="GB"
	elif [ $mem -ge 1024 ]; then
		mem=$(echo "$mem" | awk '{ printf "%.0f", $1 / 1024 }')
		fpdiv "$mem" 1024 1
		mem=${_RET}
		unit="MB"
	else
		mem="$mem"
		unit="KB"
	fi
	color b g W; printf "%s" "$mem"; color -; color g W; printf "%s%s" "$unit" "$comma"; color -; printf "%s" "$whitespace"
}

mem_available_info "$@"
