#!/bin/sh -e
#
#    menu: display the menu text
#
#    Copyright (C) 2008 Canonical Ltd.
#    Copyright (C) 2011-2012 Dustin Kirkland <kirkland@byobu.co>
#
#    Authors: Dustin Kirkland <kirkland@byobu.co>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

__menu_detail() {
	return
}

__menu() {
	local bindings esc key text
	[ -r "$BYOBU_CONFIG_DIR/keybindings" ] && bindings="$BYOBU_CONFIG_DIR/keybindings" || bindings="$BYOBU_CONFIG_DIR/.screenrc"
	if grep -qs "^source.*screen-escape-keys$" $bindings 2>/dev/null || grep -qs "^source.*f-keys.screen.disable$" $bindings 2>/dev/null || [ "$1" = "--disable-f-keys" ]; then
		# Get the second to last byte from the "escape" option
		esc=`grep "^escape" $bindings | tail -c 3 | head -c 1`
		[ -n "$esc" ] && key="^$esc-@" || key="^a-@"
	elif grep -qs "^source.*none$" $bindings 2>/dev/null; then
		key="byobu-config"
	else
		key="F9"
	fi
	text=$(gettext "Menu" 2>/dev/null) || text="Menu"
	color k w; printf "%s:<" "$text"; color -; color b k w; printf "%s" "$key"; color k w; printf ">"
}

# vi: syntax=sh ts=4 noexpandtab
