#!/bin/sh -e
#
#    mpc: print current mpd song via mpc
#
#    Copyright (C) 2008 Canonical Ltd.
#    Copyright (C) 2011-2014 Dustin Kirkland
#
#    Authors: Elan Ruusamäe <glen@pld-linux.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

__mpc_detail() {
	uname -a
}

__mpc_playing() {
	mpc status -f '' | grep -qF '[playing]'
}

__mpc() {
	__mpc_playing || return 0
	printf "%s " $(mpc current -f '[[%artist% - ]%title%]|[%file%]')
}

# vi: syntax=sh ts=4 noexpandtab
