#!/bin/sh -e
#
#    notify_osd: print notify-osd messages in the notification buffer
#
#    Copyright (C) 2010 Canonical Ltd.
#    Copyright (C) 2011-2014 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@byobu.org>
#             with help from Mathias Gug <mathias.gug@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

NOTIFY_OSD_LOG="$HOME"/.cache/notify-osd.log

__notify_osd_detail() {
	cat "$NOTIFY_OSD_LOG" || true
}

__notify_osd() {
	# This line operates basically as a daemon, watching the notify-osd log file,
	# processing new messages and sending them to the session
	CMD="tail --pid $PPID -n 0 -F $NOTIFY_OSD_LOG"
	pkill -f "$CMD" || true
	$CMD | $BYOBU_PREFIX/lib/byobu/include/notify_osd "$PPID" &
}

# vi: syntax=sh ts=4 noexpandtab
