#!/bin/sh -e
#
#    processes: report number of running processes
#
#    Copyright (C) 2008 Canonical Ltd.
#    Copyright (C) 2011 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

__processes_detail() {
	ps -ejH
}

__processes() {
	local count=$(ls -d /proc/[0-9]* 2>/dev/null| wc -l)
	[ -n "$count" ] || return
	color b y w; printf "%s" "$count"; color -; color y w; printf "&"; color --
}

# vi: syntax=sh ts=4 noexpandtab
