#!/bin/sh -e
#
#    raid: notify raid events, failures and syncing
#
#    Copyright (C) 2010 Canonical Ltd.
#    Copyright (C) 2011-2014 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@byobu.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

__raid_detail() {
	if [ -r /proc/mdstat ]; then
		cat /proc/mdstat
	elif [ "$BYOBU_OSTYPE" = "OpenBSD" ]; then
		# OpenBSD uses bioctl(8) for RAID
		bioctl softraid0 2>/dev/null || true
	else
		true
	fi
}

__raid() {
	if [ "$BYOBU_OSTYPE" = "OpenBSD" ]; then
		# OpenBSD: check softraid status via bioctl
		if bioctl softraid0 2>/dev/null | grep -qE 'Degraded|Failed|Rebuild'; then
			color B w r; printf "%s" "RAID"; color --
		fi
		return
	fi
	[ -r /proc/mdstat ] || return
	while read line; do
		local p msg
		# Errors in your raid
		case "$line" in
			*\ blocks\ *\[*_*\])
				[ -z "${msg}" ] && msg="RAID"
			;;
			*%*)
				p="${line%%\%*}${PCT}"; p=${p##* };
				[ -z "$msg" ] && msg="RAID"
				msg="$msg,$p"
			;;
		esac
	done < /proc/mdstat
	if [ -n "$msg" ]; then
		color B w r; printf "%s" "$msg"; color --
	elif [ -e "$BYOBU_RUN_DIR/status.$BYOBU_BACKEND/raid" ]; then
		# Clear out cached raid message
		rm -f "$BYOBU_RUN_DIR/status.$BYOBU_BACKEND/raid"*
	fi
}

# vi: syntax=sh ts=4 noexpandtab
