#!/bin/sh -e
#
#    session: tmux session name
#
#    Copyright (C) 2013 Dustin Kirkland <kirkland@byobu.co>
#
#    Authors: Dustin Kirkland <kirkland@byobu.co>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

__session_detail() {
	tmux list-sessions
}

__session() {
	# Note: This will only work in byobu-tmux
	local count=$(tmux list-sessions 2>/dev/null | wc -l)
	if [ $count -gt 1 ]; then
		color u W k; printf "$ICON_SESSION#S"; color --
	else
		echo
	fi
}

# vi: syntax=sh ts=4 noexpandtab
