#!/bin/sh -e
#
#    time: print the time in HH:MM:SS format
#
#    Copyright (C) 2008 Canonical Ltd.
#    Copyright (C) 2011-2014 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@byobu.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

__time_detail() {
	date
}

__time() {
	local secs=1
	[ -n "$TIME_SECONDS" ] && secs=$TIME_SECONDS
	case "$BYOBU_BACKEND" in
		screen)
			format="\0050c"
			[ "$secs" != "0" ] && format="$format:\005s"
			printf $format
		;;
	esac
}

# vi: syntax=sh ts=4 noexpandtab
