#!/bin/sh -e
#
#    trash: show icon (and optionally count) if entries in trash.
#
#    Copyright (C) 2011 Canonical Ltd.
#    Copyright (C) 2011-2014 Dustin Kirkland
#
#    Authors: James Hunt <james.hunt@canonical.com>
#             Dustin Kirkland <kirkland@byobu.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

TRASH_DIR="$HOME/.local/share/Trash/files"

__trash_detail() {
	find "$TRASH_DIR"
}

__trash() {
	local count
	[ -d "$TRASH_DIR" ] || return
	count=$(ls $dir|wc -l)
	[ "$count" = "0" ] && return
	printf "%s[%s]" "$ICON_TRASH" "$count"
}

# vi: syntax=sh ts=4 noexpandtab
