#!/bin/bash

RUNS=100

loop() {
	for j in $(seq 1 $RUNS); do
		./bin/$1 >/dev/null
	done
}

TIMEFORMAT="%R"
if [ -n "$1" ]; then
	list="$1"
else
	list=$(ls bin)
fi
for i in $list; do
	freq=`grep "byobu-status $i" ./profiles/common | awk '{print $3}'`
	echo -n "$i $freq "
	time loop $i
done
