#!/bin/bash

PKG=byobu
RUNS=100

loop() {
	for j in $(seq 1 $RUNS); do
		/usr/lib/$PKG/$1 >/dev/null
	done
}

TIMEFORMAT="%R"
if [ -n "$1" ]; then
	list="$1"
else
	list=$(ls /usr/lib/$PKG/)
fi
for i in $list; do
	freq=`grep "byobu-status $i" /usr/share/$PKG/profiles/common | awk '{print $3}'`
	echo -n "$i $freq "
	time loop $i
done
