#!/bin/sh
#
#    colors: some color values needed by all library status scripts
#
#    Copyright (C) 2014 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@byobu.co>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Default colors
# Inspired by http://design.ubuntu.com/brand/colour-palette
export BYOBU_DARK="\#333333"		# Cool grey
export BYOBU_LIGHT="\#EEEEEE"		# Warm white
export BYOBU_ACCENT="\#75507B"          # Aubergine
export BYOBU_HIGHLIGHT="\#DD4814"       # Ubuntu orange
export BYOBU_WINDOW_NAME="-"
export BYOBU_DATE="%Y-%m-%d "
export BYOBU_TIME="%H:%M:%S"
