#!/bin/sh
#
#    constants: some constant values needed by all library status scripts
#
#    Copyright (C) 2011 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG="byobu"

# UTF8 support in the hardstatus is coming one day in Screen
if [ "$UTF8" = "1" ] || [ "$BYOBU_BACKEND" = "tmux" ]; then
	#ICON_C="℃"
	#ICON_F="℉"
	ICON_C="C"
	ICON_F="F"
	ICON_RD="◂"
	ICON_WR="▸"
	ICON_MAIL="⍌"
	ICON_UP="▴"
	ICON_DN="▾"
	ICON_TRASH="♸"
	ICON_WIFI=
	ICON_REBOOT="⟳"
	ICON_UPDATES="!"
	ICON_SECURITY="‼"
	#ICON_KB="㎅"
	#ICON_MB="㎆"
	#ICON_GB="㎇"
	ICON_KB="K"
	ICON_MB="M"
	ICON_GB="G"
	ICON_TB="T"
	#ICON_KHz="㎑"
	#ICON_MHz="㎒"
	#ICON_GHz="㎓"
	ICON_KHz="KHz"
	ICON_MHz="MHz"
	ICON_GHz="GHz"
	#ICON_MBPS="㏔㎰"
	ICON_MBPS="Mb"
else
	ICON_C="C"
	ICON_F="F"
	ICON_RD="<"
	ICON_WR=">"
	ICON_MAIL="[M]"
	ICON_UP="^"
	ICON_DN="v"
	ICON_TRASH="T"
	ICON_WIFI=
	ICON_REBOOT="(R)"
	ICON_UPDATES="!"
	ICON_SECURITY="!!"
	ICON_KB="KB"
	ICON_MB="MB"
	ICON_GB="GB"
	ICON_TB="TB"
	ICON_KHz="kHz"
	ICON_MHz="MHz"
	ICON_GHz="GHz"
	ICON_MBPS="Mbps"
fi
PCT="%%"

# Support two different backends (screen/tmux)
if [ -z "$BYOBU_BACKEND" ]; then
	[ -r "/etc/byobu/backend" ] && . "/etc/byobu/backend"
	[ -r "$BYOBU_CONFIG_DIR/backend" ] && . "$BYOBU_CONFIG_DIR/backend"
fi
case "$BYOBU_BACKEND" in
	tmux)
		export BYOBU_BACKEND
		BYOBU_ARG_VERSION="-V"
		ESC=
	;;
	screen)
		export BYOBU_BACKEND="screen"
		BYOBU_ARG_VERSION="-v"
		ESC="\005"
	;;
esac

# MacOS Support
command -v gsed >/dev/null 2>&1 && export BYOBU_SED="gsed" || export BYOBU_SED="sed"
command -v greadlink >/dev/null 2>&1 && export BYOBU_READLINK="greadlink" || export BYOBU_READLINK="readlink"
command -v sensible-pager >/dev/null 2>&1 && export BYOBU_PAGER="sensible-pager" || export BYOBU_PAGER="less"

# Default colors
[ -n "$BYOBU_DARK" ] || export BYOBU_DARK="black"
[ -n "$BYOBU_LIGHT" ] || export BYOBU_LIGHT="white"
[ -n "$BYOBU_ACCENT" ] || export BYOBU_ACCENT="magenta"
[ -n "$BYOBU_HIGHLIGHT" ] || export BYOBU_HIGHLIGHT="red"
