#!/bin/sh
#
#    constants: some constant values needed by all library status scripts
#
#    Copyright (C) 2011 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@byobu.co>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

PKG="byobu"

. "${BYOBU_PREFIX}/lib/${PKG}/include/icons"

PCT="%"

# Support two different backends (screen/tmux)
if [ -z "$BYOBU_BACKEND" ]; then
	[ -r "/etc/byobu/backend" ] && . "/etc/byobu/backend"
	[ -r "$BYOBU_CONFIG_DIR/backend" ] && . "$BYOBU_CONFIG_DIR/backend"
fi
case "$BYOBU_BACKEND" in
	tmux)
		export BYOBU_BACKEND
		BYOBU_ARG_VERSION="-V"
		ESC=
	;;
	screen)
		export BYOBU_BACKEND
		BYOBU_ARG_VERSION="-v"
		ESC="\005"
	;;
esac

# MacOS Support
$BYOBU_TEST gsed >/dev/null 2>&1 && export BYOBU_SED="gsed" || export BYOBU_SED="sed"
$BYOBU_TEST greadlink >/dev/null 2>&1 && export BYOBU_READLINK="greadlink" || export BYOBU_READLINK="readlink"
$BYOBU_TEST sensible-pager >/dev/null 2>&1 && export BYOBU_PAGER="sensible-pager" || export BYOBU_PAGER="less"

# Check sed's follow-symlinks feature
$BYOBU_SED --follow-symlinks "s///" </dev/null 2>/dev/null && BYOBU_SED="$BYOBU_SED --follow-symlinks" || true

# Determine if we have ulimit support
$BYOBU_TEST ulimit >/dev/null 2>&1 && export BYOBU_ULIMIT="ulimit" || export BYOBU_ULIMIT="false"

# Find a suitable python interpreter, if undefined
if [ -z "$BYOBU_PYTHON" ]; then
	if $BYOBU_TEST python >/dev/null 2>&1; then
		BYOBU_PYTHON="python"
	elif $BYOBU_TEST python2 >/dev/null 2>&1; then
		BYOBU_PYTHON="python2"
	elif $BYOBU_TEST python3 >/dev/null 2>&1; then
		BYOBU_PYTHON="python3"
	fi
fi

# Default colors
export BYOBU_DARK="black"
export BYOBU_LIGHT="white"
export BYOBU_ACCENT="#75507B"          # AUBERGINE
export BYOBU_HIGHLIGHT="#DD4814"       # UBUNTU ORANGE
export BYOBU_WINDOW_NAME="-"
export BYOBU_DATE="%Y-%m-%d "
export BYOBU_TIME="%H:%M:%S"
