#!/bin/sh
#
#    tmux-send-command-to-all-windows
#    Copyright (C) 2014 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@byobu.org>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ $# -gt 0 ]; then
	_cmd="$*"
else
	_cmd=$(tmux show-buffer 2>/dev/null) || true
fi
[ -z "$_cmd" ] && exit 0
for w in $(tmux list-windows | $BYOBU_SED -e "s/:.*//"); do
	tmux send-keys -l -t :$w "$_cmd"
	tmux send-keys -t :$w Enter
done
unset _cmd
