#!/bin/sh -e

PKG="byobu"

# The target of the diversion somehow disappeared which will cause
# the divert removal to fail; we don't want that to happen
[ -e "/usr/bin/screen.real" ] && [ ! -e "/usr/bin/screen" ] && cp -a /usr/bin/screen.real /usr/bin/screen

# Notify users that they should reload their profile
DIR="/var/run/screen"
for d in $(ls "$DIR"); do
	touch "$DIR/$d/$PKG.reload-required"
	u=$(echo "$d" | sed "s:^S-::")
	chown $u "$DIR/$d/$PKG.reload-required"
	chmod 700 "$DIR/$d/$PKG.reload-required"
done

#DEBHELPER#
