#!/bin/sh -e

PKG="byobu"

if [ -x "/usr/bin/screen.real" ]; then
	# Byobu used to divert the real /usr/bin/screen, but we don't
	# do this anymore; clean up old diversion if upgrading
        dpkg-divert --package "$PKG" --rename --remove /usr/bin/screen
fi

#DEBHELPER#
