#!/bin/sh -e

PKG="byobu"

# Remove helper symlinks
for i in /usr/bin/screen-profiles-status /usr/bin/screen-launcher; do
	[ -h "$i" ] && rm -f "$i"
done
rm -f /etc/profile.d/$PKG.sh

true

#DEBHELPER#
