#!/bin/sh -e

if dpkg --compare-versions "$2" lt-nl 2.0; then
	if [ -e "/usr/bin/screen.real" ]; then
		if [ ! -e "/usr/bin/screen" ]; then
			# The target of the diversion somehow disappeared
			# which will cause the divert removal to fail;
			# we don't want that to happen
			cp -a /usr/bin/screen.real /usr/bin/screen
		fi
		# clean up old screen diversion
		dpkg-divert --package screen-profiles --rename --remove /usr/bin/screen || true
	fi
fi

#DEBHELPER#
