#!/bin/sh
# This script should be run during in the './debian/rules get-orig-source'
# step.

for i in $(ls profiles/logos); do
	echo "Generating profile: $i-light"
	cat profiles/profile.skel > profiles/$i-light
	logo="`cat profiles/logos/$i`"
	sed -i "s/__LOGO__/$logo/" profiles/$i-light
	echo "Generating profile: $i-dark"
	cp profiles/$i-light profiles/$i-dark
	grep "^caption " profiles/common >> profiles/$i-dark
	sed -i "s/ Wk/ Kw/g" profiles/$i-dark
	sed -i "s/kW/wK/g" profiles/$i-dark
done
