#!/bin/sh
# This script should be run during in the './debian/rules get-orig-source'
# step.

for i in $(ls profiles/logos); do
	rm -f profiles/$i*
	if [ "$1" = "--clean" ]; then
		echo "Removing profiles for: $i"
		continue
	fi
	echo "Generating profiles for: $i"
	cat profiles/profile.skel > profiles/$i-light
	logo="`cat profiles/logos/$i`"
	sed -i "s/__LOGO__/$logo/" profiles/$i-light
	cp profiles/$i-light profiles/$i-dark
	sed -i "s/ Wk/ Kw/g" profiles/$i-dark
	sed -i "s/kW/wK/g" profiles/$i-dark
	for j in "B-light_blue" "b-dark_blue" "C-light_cyan" "c-dark_cyan" "G-light_green" "g-dark_green" "M-light_purple" "m-dark_purple" "R-light_red" "r-dark_red" "Y-light_yellow" "y-dark_yellow" "k-black"; do
		x=$(echo "$j" | awk -F"-" '{print $1}')
		desc=$(echo "$j" | awk -F"-" '{print $2}')
		y="w"
		if echo "$desc" | grep -qs "light"; then
			y="k"
		fi
		cp profiles/$i-light profiles/$i-$desc
		sed -i "s/ Wk/ $x$y/g" profiles/$i-$desc
		sed -i "s/kW/$y$x/g" profiles/$i-$desc
	done
done
