.TH TRUSTMUX-ENABLE 1 "2026-05-28" "trustmux" "User Commands"
.SH NAME
trustmux\-enable \- start the Trustmux daemon and enable it at login
.SH SYNOPSIS
.B trustmux\-enable
.SH DESCRIPTION
.B trustmux\-enable
runs the first-time setup wizard if needed, starts the Trustmux daemon,
and installs a shell login hook so the daemon starts automatically on
future logins.
.SH SEE ALSO
.BR trustmux (1),
.BR trustmux (1),
.BR trustmux\-disable (1)
.SH AUTHOR
Dustin Kirkland <kirkland@ubuntu.com>
