.TH TRUSTMUX-DISABLE 1 "2026-05-28" "trustmux" "User Commands"
.SH NAME
trustmux\-disable \- stop the Trustmux daemon and disable it at login
.SH SYNOPSIS
.B trustmux\-disable
.SH DESCRIPTION
.B trustmux\-disable
stops the running Trustmux daemon and removes the login hook installed
by
.BR trustmux\-enable (1),
so the daemon will not start automatically on future logins.
.SH SEE ALSO
.BR trustmux (1),
.BR trustmux\-ctl (1),
.BR trustmux\-enable (1)
.SH AUTHOR
Dustin Kirkland <kirkland@ubuntu.com>
