#!/bin/sh

# To disable this MOTD appendage:
#  sudo touch /etc/byobu/disable-motd

if [ ! -e /etc/profile.d/Z98-byobu.sh ] && [ ! -e /etc/byobu/disable-motd ]; then
	echo
	echo "For a premium command line experience, enable Ubuntu's text-based window manager:"
	echo "  byobu-enable"
fi
