.TH byobu-ctrl-a 1 "10 May 2011" byobu "byobu"
.SH NAME
byobu\-ctrl\-a \- Configure Byobu's ctrl-a behavior

.SH DESCRIPTION
\fBbyobu\-ctrl\-a\fP is an interactive program that allows a user to configure the behavior of the 'ctrl-a' key sequence.

Traditional GNU \fBscreen\fP(1) uses ctrl-a as its escape character, while GNU \fBemacs\fP(1) uses ctrl-a to move the cursor to the beginning of the line.  This conflict has caused unending amounts of grief among Screen, Byobu, and Emacs-mode users.

Thus, this program exists to allow each user to choose the behavior of ctrl-a in their local environment.

.TP
\fIhttp://byobu.org\fP
.PD

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@byobu.org> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document and the utility under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

The complete text of the GNU General Public License can be found in \fI/usr/share/common-licenses/GPL\fP on Debian/Ubuntu systems, or in \fI/usr/share/doc/fedora-release-*/GPL\fP on Fedora systems, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
