.TH byobu-janitor 1 "6 January 2011" byobu "byobu"
.SH NAME
byobu-janitor \- script for cleaning and upgrading environment after upgrades

.SH SYNOPSIS
\fBbyobu-janitor\fP

.SH DESCRIPTION
\fBbyobu-janitor\fP is script for cleaning environment after upgrades, it consists from several tasks where aim is to ensure that environment is ready for new version of byobu.

.SH "BUGS"

None found, yet.

.SH SEE ALSO
.PD 0
.TP
\fBscreen\fP(1), \fBbyobu-config\fP(1), \fBbyobu-export\fP(1), \fBbyobu-status\fP(1), \fBbyobu-status-detail\fB(1)
.TP
\fBhttp://byobu.org\fP
.PD

.SH AUTHOR
This manpage was written by Jan Klepek <jan.klepek at gmail.com> and the utility was written by Dustin Kirkland <kirkland@byobu.org> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

The complete text of the GNU General Public License can be found in \fI/usr/share/common-licenses/GPL\fP on Debian/Ubuntu systems, or in \fI/usr/share/doc/fedora-release-*/GPL\fP on Fedora systems, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
