.TH byobu-quiet 1 "10 May 2011" byobu "byobu"
.SH NAME
byobu\-quiet \- Silence all of Byobu's status indicators and eliminate the hardstatus line

.SH USAGE
byobu\-quiet [\-\-undo]

.SH DESCRIPTION
\fBbyobu\-quiet\fP will disable ALL of Byobu's status indicators and eliminate the hardstatus line.

Some administrators, in some environments, at some times may prefer a very minimal, quiet Byobu, without the potentially distracting status indicators and eye candy.  However, the window menu is preserved, as well as all of Byobu's keybindings and helper utilities.  To elminate the window list, use \fBbyobu-silent\fP(1).

.SH SEE ALSO
\fBbyobu-silent\fP(1)

.TP
\fIhttp://byobu.org\fP
.PD

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@byobu.org> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document and the utility under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

The complete text of the GNU General Public License can be found in \fI/usr/share/common-licenses/GPL\fP on Debian/Ubuntu systems, or in \fI/usr/share/doc/fedora-release-*/GPL\fP on Fedora systems, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
