.TH byobu\-shell 1 "11 Feb 2009" byobu "byobu"
.SH NAME
byobu\-shell \- Print the message of the day and launch a shell

.SH DESCRIPTION
\fBbyobu\-shell\fP is a simple script that prints the message of the day (/etc/motd) and launches a shell.

$SHELL will be invoked if it exists.  Otherwise, /bin/sh will be used.

.TP
\fIhttp://byobu.org\fP
.PD

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@byobu.org> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document and the utility under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

The complete text of the GNU General Public License can be found in \fI/usr/share/common-licenses/GPL\fP on Debian/Ubuntu systems, or in \fI/usr/share/doc/fedora-release-*/GPL\fP on Fedora systems, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
