.TH byobu-config 1 "16 Jan 2009" byobu "byobu"
.SH NAME
byobu-config \- Configuration utility for byobu

.SH DESCRIPTION
\fBbyobu\-config\fP is an application that can configure a number of options available in the byobu utility.

The menu provided by the \fBbyobu\fP should be self-explanatory.


.SH "SEE ALSO"
.PD 0
.TP
\fBscreen\fP(1)

.TP
\fIhttp://byobu.org\fP
.PD

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@byobu.org> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document and the utility under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

The complete text of the GNU General Public License can be found in \fI/usr/share/common-licenses/GPL\fP on Debian/Ubuntu systems, or in \fI/usr/share/doc/fedora-release-*/GPL\fP on Fedora systems, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
