.TH byobu-prompt 1 "26 July 2013" byobu "byobu"
.SH NAME
byobu-prompt, byobu-enable-prompt, byobu-disable-prompt \- add and remove a nice color prompt to your shell configuration

.SH SYNOPSIS
\fBbyobu-prompt\fP
.TP
\fBbyobu-enable-prompt\fP
.TP
\fBbyobu-disable-prompt\fP

.SH DESCRIPTION

Byobu provides a special PS1 prompt command, compatible with Bash shells.  It will display the previous command's exit code, if it's not zero.  It will use 3 separate colors for the local username, hostname, and the current working directory.

\fBbyobu-enable-prompt\fP will add one line to your \fI~/.bashrc\fP.

You can safely remove the line from your \fI~/.bashrc\fP, which ends in \fB#byobu-prompt\fP.

\fBbyobu-disable-prompt\fP will remove its color configuration from \fI~/.bashrc\fP.

\fBbyobu-prompt\fP is an interactive wrapper of the previous two tools.

.SH "BUGS"

This is currently only compatible with \fBbash(1)\fP.

.SH SEE ALSO
.PD 0
.TP
\fBbash\fP(1)
.TP
\fBhttp://byobu.org\fP
.PD

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@byobu.org> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

The complete text of the GNU General Public License can be found in \fI/usr/share/common-licenses/GPL\fP on Debian/Ubuntu systems, or in \fI/usr/share/doc/fedora-release-*/GPL\fP on Fedora systems, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
