.TH byobu\-export 1 "2 Aug 2010" byobu "byobu"
.SH NAME
byobu\-export \- DEPRECATED

.SH SYNOPSIS
.BI "byobu\-export"

.SH DESCRIPTION
The \fBbyobu\-export\fP utility is now deprecated.

To install byobu on a system for which byobu is not packaged, or
where you are not the root user, simply:
 * Download the latest release (>= 3.0) from:
    https://launchpad.net/byobu/+download
 * And follow the instructions in the README

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@byobu.org> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document and the utility under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

The complete text of the GNU General Public License can be found in \fI/usr/share/common-licenses/GPL\fP on Debian/Ubuntu systems, or in \fI/usr/share/doc/fedora-release-*/GPL\fP on Fedora systems, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
