.TH byobu-silent 1 "21 May 2011" byobu "byobu"
.SH NAME
byobu\-silent\- Silence all of Byobu's status indicators, eliminate the hardstatus line, and the window list

.SH USAGE
byobu\-silent [\-\-undo]

.SH DESCRIPTION
\fBbyobu\-silent\fP will disable ALL of Byobu's status indicators, eliminate the hardstatus line, and the window list.

Some administrators, in some environments, at some times may prefer a very minimal, quiet Byobu, without the potentially distracting status indicators and eye candy.

\fBbyobu-silent\fP implies \fBbyobu-quiet\fP.

.SH SEE ALSO
\fBbyobu-quiet\fP(1)

.TP
\fIhttp://byobu.org\fP
.PD

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@byobu.org> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document and the utility under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

The complete text of the GNU General Public License can be found in \fI/usr/share/common-licenses/GPL\fP on Debian/Ubuntu systems, or in \fI/usr/share/doc/fedora-release-*/GPL\fP on Fedora systems, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
