.TH byobu\-select\-backend 1 "30 Oct 2011" byobu "byobu"
.SH NAME
byobu\-select\-backend \- select your default Byobu backend window manager

.SH SYNOPSIS
\fBbyobu\-select\-backend\fP [screen|tmux]

.SH DESCRIPTION
\fBbyobu\-select\-backend\fP is an application that lists the available Byobu backends and allows you to select your default.

You can select one of either \fBscreen\fP(1) or \fBtmux\fP(1) on the command line, or giving no command line parameters, the utility will run interactively.

This utility will only affect which backend is used by default when simply running, \fBbyobu\fP(1).  Note that at any time, you can force the backend of a particular session by running the helpers, \fBbyobu-screen\fP(1) or \fBbyobu-tmux\fP(1).

.SH FILES
\fI~/.byobu/backend\fP

.SH "SEE ALSO"
.PD 0
.TP
\fBbyobu\fP(1), \fBbyobu-screen\fP(1), \fBbyobu-tmux\fP(1), \fBscreen\fP(1), \fBtmux\fP(1)

.TP
\fIhttp://byobu.org\fP
.PD

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@byobu.org> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document and the utility under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

The complete text of the GNU General Public License can be found in \fI/usr/share/common-licenses/GPL\fP on Debian/Ubuntu systems, or in \fI/usr/share/doc/fedora-release-*/GPL\fP on Fedora systems, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
