.TH byobu\-launcher 1 "16 Jan 2009" byobu "byobu"
.SH NAME
byobu\-launcher \- Byobu Launcher

.SH DESCRIPTION
\fBbyobu\-launcher\fP is a simple application that will launch \fBscreen\fP(1) in a \fBbyobu\fP(1) configuration, reconnecting to an existing detached session (if available).

.SH "SEE ALSO"
.PD 0
.TP
\fBscreen\fP(1), \fBbyobu\fP(1)

.TP
\fIhttp://byobu.org\fP
.PD

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@byobu.org> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document and the utility under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

The complete text of the GNU General Public License can be found in \fI/usr/share/common-licenses/GPL\fP on Debian/Ubuntu systems, or in \fI/usr/share/doc/fedora-release-*/GPL\fP on Fedora systems, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
