.TH byobu-keybindings 1 "7 May 2013" byobu "byobu"
.SH NAME
byobu-keybindings \- toggle on/off Byobu's keybindings

.SH SYNOPSIS
\fBbyobu-keybindings\fP

.SH DESCRIPTION
\fBbyobu-keybindings\fP toggles on and off Byobu's keybindings in the current \fBtmux\fP(1) or \fBscreen\fP(1) session.  It will only operate against the current session.

This executable is provided as an alternative to pressing <Shift>-F12, and is useful in environments where <Shift>-F12 does not work (e.g., on the Linux console TTY).

Some Byobu users toggle these keybindings when they interfere with other programs using the same keybindings (e.g., \fBmc\fP(1)).

.SH SEE ALSO
.PD 0
.TP
\fBscreen\fP(1), \fBtmux\fP(1), \fBbyobu\fP(1), \fBmc\fP(1)
.TP
\fBhttp://byobu.org\fP
.PD

.SH AUTHOR
This manpage and utility were written by Dustin Kirkland <kirkland@byobu.org> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

The complete text of the GNU General Public License can be found in \fI/usr/share/common-licenses/GPL\fP on Debian/Ubuntu systems, or in \fI/usr/share/doc/fedora-release-*/GPL\fP on Fedora systems, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
