.TH byobu-layout 1 "8 Jan 2012" byobu "byobu"
.SH NAME
byobu\-layout \- Save and restore byobu-tmux layouts

.SH USAGE
byobu\-layout [save|restore] [name]

.SH DESCRIPTION
\fBbyobu\-layout\fP will save and restore \fBbyobu-tmux\fP(1) split window layouts.

If 'name' is blank, it operates interactively.

Note that this only works with Byobu when backed by \fBtmux\fP(1), and not \fBscreen\fP(1).

.SH SEE ALSO
\fBbyobu\fP(1), \fBtmux\fP(1)

.TP
\fIhttp://byobu.co\fP
.PD

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@byobu.co> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document and the utility under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

The complete text of the GNU General Public License can be found in \fI/usr/share/common-licenses/GPL\fP on Debian/Ubuntu systems, or in \fI/usr/share/doc/fedora-release-*/GPL\fP on Fedora systems, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
