.TH manifest 1 "28 February 2016" byobu "byobu"
.SH NAME
manifest \- import or export a package list

.SH SYNOPSIS
\fBmanifest\fP export [-|URL|FILENAME]
.TP
\fBmanifest\fP import -|URL|FILENAME
.TP

.SH DESCRIPTION


.SH "BUGS"

This is currently only compatible with \fBapt(8)\fP and \fBdpkg\fP(1).

.SH SEE ALSO
.PD 0
.TP
\fBapt\fP(8), \fBdpkg\fP(1), \fBpastebinit\fP(1)
.TP
\fBhttp://byobu.org\fP
.PD

.SH AUTHOR
This manpage and the utility were written by Dustin Kirkland <kirkland@byobu.org> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

The complete text of the GNU General Public License can be found in \fI/usr/share/common-licenses/GPL\fP on Debian/Ubuntu systems, or in \fI/usr/share/doc/fedora-release-*/GPL\fP on Fedora systems, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
