.TH vigpg 1 "25 Apr 2014" byobu "byobbyobuu"
.SH NAME
vigpg \- open and edit an encrypted file

.SH SYNOPSIS
\fBvigpg\fP [FILE]

.SH DESCRIPTION
\fBvigpg\fP is a program that wraps your editor and gpg to edit an encrypted file

This may be useful, for instance, to edit your password file

.SH EXAMPLE
 $ vigpg passwords.txt.gpg

.SH SEE ALSO
\fBgpg\fP(1)\fP, \fBsensible-editor\fP(1)

.SH AUTHOR
This manpage and the utility was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
