.TH wifi-status 1 "27 Sep 2010" byobu "byobu"
.SH NAME
wifi-status \- monitor the wireless interface

.SH SYNOPSIS
\fBwifi-status\fP [INTERFACE]

.SH DESCRIPTION
\fBwifi-status\fP is a program that monitors a wireless interface.

This is often useful when trying to associate with an access point.

.SH SEE ALSO
\fBiwconfig\fP(8)\fP, \fBip\fP(8)

.SH AUTHOR
This manpage and the utility was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL, or on the web at \fIhttp://www.gnu.org/licenses/gpl.txt\fP.
